# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'SpeactralChatProto' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
pod 'Firebase'
pod 'Firebase/Database'
pod 'Firebase/Auth'
pod 'JSQMessagesViewController'
pod 'FirebaseInstanceID'
pod 'FirebaseMessaging'
pod 'FirebaseStorage'
pod 'SwiftKeychainWrapper'
pod 'NMPopUpViewSwift'
pod 'SDWebImage-ProgressView'
  # Pods for SpeactralChatProto

end
